example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_wishlist_ajax, show_xml, show_json, show_json_by_id, show_xml_by_id, register, login_user, logout_user, submit_ajax_form
app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name = 'show_json'),
    path('json/<int:id>', show_json_by_id, name = 'show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name = 'show_xml_by_id'),
    path('register/', register, name = "register"),
    path('login/', login_user, name = "login"),
    path('logout/', logout_user, name = "logout"),
    path('ajax/', show_wishlist_ajax, name = "show_wishlist_ajax"),
    path('ajax/submit/', submit_ajax_form, name = "wishlist_ajax_submit")
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render, redirect
from wishlist.models import BarangWishlist
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
import datetime

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Alvaro',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if(request.method == "POST"):
        form = UserCreationForm(request.POST)
        if(form.is_valid):
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) 
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    return render(request, "wishlist_ajax.html", {})

@login_required(login_url='/wishlist/login/')
def submit_ajax_form(request):
    if(request.method == "POST"):
        nama_barang = request.POST.get("nama_barang")
        harga_barang = request.POST.get("harga_barang")
        deskripsi = request.POST.get("deskripsi")
        validate = BarangWishlist(nama_barang = nama_barang, harga_barang = harga_barang, deskripsi = deskripsi)
        validate.save()
        return JsonResponse({"data": {
            "nama_barang": nama_barang,
            "harga_barang": harga_barang,
            "deskripsi": deskripsi
        }})

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/submit_ajax.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>

<head>
    {% block meta %}
    <title> Create Wishlist </title>
    {% endblock meta %}
</head>

<body>
{% block content %}

<div class = "flex flex-col items-center justify-center position-center login-color box-shadow">
    <div class = "login rounded-md font-bold p-8 w-full max-w-720px">
        <h1 class = "text-center">Create Task</h1>

        <form method="POST" action="http://localhost:8000/wishlist/ajax/submit/">
            {% csrf_token %}
            <div class = "p-8">
                <div class = "my-4">
                    <p>Nama Barang: </p>
                    <input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control">
                
                </div>
                        
                <div class = "my-4">
                    <p>Harga: </p>
                    <input type="number" name="harga_barang" placeholder="Harga" class="form-control">
                </div>
                
                <div class = "my-4">
                    <p>Deskripsi: </p>
                    <input type="description" name="deskripsi" placeholder="Deskripsi" class="form-control">
                </div>

                <div class = "text-center">
                    <button class="btn btn-primary w-full" type="submit" id = "idForm"> Create Wishlist </button>
                </div>
            </div>
        </form>
     </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    $("#idForm").submit(function(e) {
        e.preventDefault();

        var form = $(this);
        var actionUrl = form.attr('action');

        $.ajax({
            type: "POST",
            url: actionUrl,
            data: form.serialize(), // serializes the form's elements.
            success: function(data){
                alert(data); // show response from the php script.
            }
        });

    });
</script>

{% endblock content %}
</body>
</html>

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"> {{nama}} </a>
      <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
    </div>
  </nav>

<h5>Nama: </h5>
<p> {{nama}}</p>

<table>
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
</table>
<h5>Sesi terakhir login: {{ last_login }}</h5>
<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
    <head>
    </head>

<body>
    {% block content %}
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="#"> {{nama}} </a>
            <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
            </div>
        </nav>

        <h5>Nama: </h5>
        <p> Alvaro </p>

        <table>
            <div style="padding:16px">
                <tr> 
                    <th style = "padding:8px;"> Nama Barang </th>
                    <th style = "padding:8px;"> Harga Barang </th>
                    <th style = "padding:8px;"> Deskripsi </th> 
                </tr>
            </div>
            <div id = "div" style="padding:16px"> </div>
        </table>
        <h5>Sesi terakhir login: </h5>
        <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

        
        <form id = "idForm" method="POST" action="/wishlist/ajax/submit/">
            {% csrf_token %}
            <div class = "p-8">
                <div class = "my-4">
                    <p>Nama Barang: </p>
                    <input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control">
                
                </div>
                        
                <div class = "my-4">
                    <p>Harga: </p>
                    <input type="number" name="harga_barang" placeholder="Harga" class="form-control">
                </div>
                
                <div class = "my-4">
                    <p>Deskripsi: </p>
                    <input type="description" name="deskripsi" placeholder="Deskripsi" class="form-control">
                </div>

                <div class = "text-center">
                    <button class="btn btn-primary w-full" type="submit" id = "idForm"> Create Wishlist </button>
                </div>
            </div>
        </form>






        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


        <script>
            function showData(){
                $.get("/wishlist/json/", function(data)
                    {   
                        $.each(data, function(i,data){
                            var th_nama_barang =
                            `<th style = "padding:8px;"> ${data.fields.nama_barang} </th>`;
                            $(th_nama_barang).appendTo("#tr");

                            var th_harga_barang =
                            `<th style = "padding:8px;"> ${data.fields.harga_barang} </th>`;

                            var th_deskripsi_barang =
                            `<th style = "padding:8px;"> ${data.fields.deskripsi} </th>`;

                            var total = `<tr> ${th_nama_barang} ${th_harga_barang} ${th_deskripsi_barang} </tr>`

                            $(total).appendTo("#div");
                        });
                    });
                    return false;
            }
                $(document).ready(function(){
                    showData()
                });


            $("#idForm").submit(function(event) {
                event.preventDefault();

                var form = $(this);
                var actionUrl = form.attr('action');

                $.ajax({
                    type: "POST",
                    url: actionUrl,
                    data: form.serialize(),
                    success: function(data){
                        console.log(data)
                        var th_nama_barang =
                            `<th style = "padding:8px;"> ${data.data.nama_barang} </th>`;
                            $(th_nama_barang).appendTo("#tr");

                            var th_harga_barang =
                            `<th style = "padding:8px;"> ${data.data.harga_barang} </th>`;

                            var th_deskripsi_barang =
                            `<th style = "padding:8px;"> ${data.data.deskripsi} </th>`;

                            var total = `<tr> ${th_nama_barang} ${th_harga_barang} ${th_deskripsi_barang} </tr>`

                            $(total).appendTo("#div");                  
                    }
                });

            });
        </script>

    {% endblock content %}
</body>

</html>